// Netlify Edge Function: Server-side dynamic Open Graph & Twitter Card injection for crawlers
// Automatically serves product/pack images & titles when links are shared on Facebook, WhatsApp, Twitter, etc.

const BOT_USER_AGENTS = [
  'facebookexternalhit',
  'facebot',
  'facebookcatalog',
  'twitterbot',
  'whatsapp',
  'telegrambot',
  'linkedinbot',
  'discordbot',
  'slackbot',
  'pinterest',
  'skypeuripreview',
  'meta-externalagent',
  'google-inspectiontool',
  'applebot',
  'bytespider',
  'yandexbot',
  'bingbot',
  'crawler',
  'spider',
];

function isCrawler(userAgent) {
  if (!userAgent) return false;
  const ua = userAgent.toLowerCase();
  return BOT_USER_AGENTS.some((bot) => ua.includes(bot));
}

function escapeHtml(str) {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

export default async (request, context) => {
  const url = new URL(request.url);
  const userAgent = request.headers.get('user-agent') || '';

  // Only run server-side dynamic meta injection for social crawlers/bots or when ?_og=1 is present
  const isBot = isCrawler(userAgent) || url.searchParams.get('_og') === '1';

  if (!isBot) {
    return context.next();
  }

  const pathname = url.pathname;

  // Skip non-product shop routes
  if (
    pathname === '/shop' ||
    pathname === '/shop/' ||
    pathname.startsWith('/shop/cart') ||
    pathname.startsWith('/shop/checkout') ||
    pathname.startsWith('/shop/orders')
  ) {
    return context.next();
  }

  // Check if pack or single product
  const packMatch = pathname.match(/^\/shop\/pack\/([^/?#]+)/);
  const productMatch = pathname.match(/^\/shop\/([^/?#]+)/);

  let metaTitle = '';
  let metaDescription = '';
  let metaImage = '';
  const metaUrl = `https://gympilot.tn${pathname}`;

  try {
    if (packMatch) {
      const packIdOrSlug = packMatch[1];
      const apiRes = await fetch(`https://api.gympilot.tn/api/packs/${packIdOrSlug}`, {
        headers: { Accept: 'application/json' },
        signal: AbortSignal.timeout(4000),
      });

      if (apiRes.ok) {
        const pack = await apiRes.json();
        metaTitle = `${pack.name} — Offre Spéciale GymPilot`;
        metaDescription = pack.tagline || pack.description || `Offre spéciale ${pack.name} avec livraison express sur GymPilot Shop.`;
        metaImage = pack.images?.[0] || 'https://gympilot.tn/og-image.jpg';
      }
    } else if (productMatch) {
      const productId = productMatch[1];
      const apiRes = await fetch(`https://api.gympilot.tn/api/products/${productId}`, {
        headers: { Accept: 'application/json' },
        signal: AbortSignal.timeout(4000),
      });

      if (apiRes.ok) {
        const product = await apiRes.json();
        metaTitle = `${product.name} — GymPilot Shop`;
        const rawDesc = product.description ? product.description.replace(/\s+/g, ' ').trim() : '';
        metaDescription = rawDesc ? (rawDesc.length > 200 ? rawDesc.slice(0, 197) + '...' : rawDesc) : `Achetez ${product.name} authentique avec livraison rapide sur GymPilot Shop.`;
        metaImage = product.images?.[0] || 'https://gympilot.tn/og-image.jpg';
      }
    }
  } catch (err) {
    // If backend request fails or times out, fallback to normal SPA response
    console.error('Edge function Open Graph fetch error:', err);
    return context.next();
  }

  // If no product/pack data found, proceed normally
  if (!metaTitle || !metaImage) {
    return context.next();
  }

  // Get downstream index.html
  const response = await context.next();
  const html = await response.text();

  const safeTitle = escapeHtml(metaTitle);
  const safeDesc = escapeHtml(metaDescription);
  const safeImage = escapeHtml(metaImage);
  const safeUrl = escapeHtml(metaUrl);

  const ogTags = [
    `  <!-- Dynamic Product Open Graph Generated by GymPilot Edge Function -->`,
    `  <title>${safeTitle}</title>`,
    `  <meta name="description" content="${safeDesc}" />`,
    `  <meta property="og:type" content="product" />`,
    `  <meta property="og:site_name" content="GymPilot" />`,
    `  <meta property="og:title" content="${safeTitle}" />`,
    `  <meta property="og:description" content="${safeDesc}" />`,
    `  <meta property="og:image" content="${safeImage}" />`,
    `  <meta property="og:image:secure_url" content="${safeImage}" />`,
    `  <meta property="og:image:alt" content="${safeTitle}" />`,
    `  <meta property="og:url" content="${safeUrl}" />`,
    `  <meta name="twitter:card" content="summary_large_image" />`,
    `  <meta name="twitter:title" content="${safeTitle}" />`,
    `  <meta name="twitter:description" content="${safeDesc}" />`,
    `  <meta name="twitter:image" content="${safeImage}" />`,
  ].join('\n');

  // Strip existing static fallback title & og tags from index.html head to prevent duplicates
  let modifiedHtml = html
    .replace(/<title>.*?<\/title>/is, '')
    .replace(/<meta\s+name=["']description["'][^>]*>/gi, '')
    .replace(/<meta\s+property=["']og:[^"']+["'][^>]*>/gi, '')
    .replace(/<meta\s+name=["']twitter:[^"']+["'][^>]*>/gi, '')
    .replace('</head>', `${ogTags}\n</head>`);

  return new Response(modifiedHtml, {
    status: 200,
    headers: {
      'content-type': 'text/html; charset=utf-8',
      'cache-control': 'public, max-age=300, s-maxage=3600',
    },
  });
};
